import type { ExplainQuestion } from '../../core/store/sessionStore';

// Ordered from the basics (units, v = ωr) up to the tutorial-style problems
// (turntable, cords, puck on a table, vertical circle).
export const CIRCULAR_EXPLAIN_QUESTIONS: ExplainQuestion[] = [
  {
    id: 'rpm-to-rads',
    question: 'A record spins at 60 revolutions per minute. What is its angular velocity in rad/s?',
    options: ['6.3 rad/s', '60 rad/s', '1.0 rad/s', '377 rad/s'],
    correctIndex: 0,
    hint: 'One revolution is 2π radians, and one minute is 60 seconds. Multiply the revolutions per minute by 2π, then divide by 60.',
    explanation: '60 rpm is one turn every second, and one turn is 2π ≈ 6.28 radians, so ω ≈ 6.3 rad/s. The other numbers come from mixing up the conversion: 60 leaves the units as rpm, 1.0 is the frequency in turns per second, and 377 multiplies by 2π but forgets to divide by 60.',
  },
  {
    id: 'same-omega-different-speed',
    question: 'Two coins sit on a spinning record, one 5 cm from the centre and the other 10 cm from the centre. How do they compare?',
    options: [
      'The same angular velocity, but the outer coin moves twice as fast',
      'The same speed, but the outer coin has twice the angular velocity',
      'The same angular velocity and the same speed',
      'The outer coin has twice the angular velocity and moves twice as fast',
    ],
    correctIndex: 0,
    hint: 'Both coins make one full turn in the same time. Which of them has the bigger circle to cover in that time?',
    explanation: 'Everything on a rigid spinning disc turns through the same angle in the same time, so ω is the same for both. But v = ωr, so the coin at twice the radius moves at twice the speed. The outer coin covers a bigger circle in the same time.',
  },
  {
    id: 'centripetal-speed-doubled',
    question: 'A car goes round a bend of fixed radius. If it doubles its speed, what happens to the centripetal acceleration it needs?',
    options: ['It quadruples', 'It doubles', 'It halves', 'It stays the same'],
    correctIndex: 0,
    hint: 'The formula is a = v²/r. Is the speed multiplied once, or squared?',
    explanation: 'a = v²/r depends on the SQUARE of the speed, so doubling v multiplies a by 2² = 4. The net inward force must grow by the same factor, which is why a car that is fine at 30 km/h can skid at 60 km/h on the very same bend.',
  },
  {
    id: 'angular-accel-stopping',
    question: 'A fan blade spinning at 120 rad/s is switched off and slows steadily to rest in 6.0 s. What is its angular acceleration?',
    options: ['−20 rad/s²', '+20 rad/s²', '−720 rad/s²', '−0.05 rad/s²'],
    correctIndex: 0,
    hint: 'α = (ω_final − ω_initial) ÷ time. The final angular velocity is zero. What sign should the answer have for something that is slowing down?',
    explanation: 'α = (0 − 120) ÷ 6.0 = −20 rad/s². The minus sign says the blade is slowing down, since ω is positive and decreasing. (−720 multiplies instead of dividing, and −0.05 divides the wrong way round.)',
  },
  {
    id: 'real-force-turntable',
    question: 'A coin rides steadily on a turntable. Which real force, acting on the coin, keeps it moving in a circle?',
    options: [
      'Static friction from the turntable, pointing toward the centre',
      'A centrifugal force pointing outward from the centre',
      'The coin\'s weight, pointing downward',
      'The normal force from the turntable, pointing upward',
    ],
    correctIndex: 0,
    hint: 'The circle is horizontal, so the force that does the turning must be horizontal. Which of the forces on the coin act sideways rather than up or down?',
    explanation: 'The weight and the normal force are vertical and cancel each other. The only horizontal force on the coin is the static friction from the turntable, and it points toward the centre. Friction IS the centripetal force here. A "centrifugal force" is not a real force acting on the coin.',
  },
  {
    id: 'path-after-release',
    question: 'A ball is whirled in a horizontal circle on a string, and you watch from above. The string suddenly snaps. Ignoring the downward pull of gravity, which path does the ball follow, as seen from above?',
    options: [
      'A straight line along the direction it was moving at that instant (the tangent)',
      'A straight line outward, along the radius',
      'It keeps circling for a while, then flies off',
      'A spiral that curves outward',
    ],
    correctIndex: 0,
    hint: 'Once the string snaps, what real force is left acting sideways on the ball? And what does Newton\'s first law say about an object with no net force?',
    explanation: 'With the string gone there is no sideways force at all, so by Newton\'s first law the ball continues in a straight line at constant velocity: the velocity it had at the moment of release, which was along the tangent to the circle. It is not flung outward. Nothing pushes it outward; it just stops being pulled inward.',
  },
  {
    id: 'mu-from-rpm',
    question: 'A coin on a turntable slips when the turntable reaches 60 rpm. The coin is 10 cm from the axis. What is the coefficient of static friction? (g = 9.8 m/s²)',
    options: ['0.40', '0.064', '0.040', '0.63'],
    correctIndex: 0,
    hint: 'At the point of slipping, friction is at its maximum: μmg = mω²r, so μ = ω²r/g. Convert the rpm to rad/s first, and remember that r must be in metres.',
    explanation: '60 rpm is ω = 2π = 6.28 rad/s, and r = 0.10 m. Then μ = ω²r/g = (39.5 × 0.10)/9.8 ≈ 0.40. The wrong answers come from slips: 0.063 is ωr/g (a square missing), 0.040 is v²/g (the radius squared instead of ω²), and 0.63 is just ωr, with the division by g forgotten.',
  },
  {
    id: 'mass-cancels-turntable',
    question: 'A coin is replaced by a heavier coin of the same material, placed at the same distance from the axis. Compared with the first coin, when does it slip?',
    options: [
      'At the same turntable speed: the extra weight and the extra friction cancel',
      'Sooner, because a heavier coin needs a larger force',
      'Later, because a heavier coin presses harder and has more friction',
      'It cannot be predicted without knowing the mass',
    ],
    correctIndex: 0,
    hint: 'Write the two sides of mω²r = μmg. Is there an m on both sides?',
    explanation: 'The friction needed is mω²r and the most friction available is μmg. Both contain m, so it cancels, leaving ω² r = μ g. The slipping speed depends only on μ and r, not on the mass. A heavier coin needs more force to turn, but the turntable also grips it harder.',
  },
  {
    id: 'radius-quarter',
    question: 'A coin 4 cm from the axis only just stays on a turntable at 90 rpm. The turntable is now run at 180 rpm. How far from the axis must the coin be for it to only just stay on?',
    options: ['1 cm', '2 cm', '8 cm', '4 cm'],
    correctIndex: 0,
    hint: 'At the point of slipping, ω²r = μg is the same fixed number every time. If ω doubles, what happens to ω², and so what must happen to r?',
    explanation: 'ω² r = μ g is constant, so r is proportional to 1/ω². Doubling ω multiplies ω² by 4, so r must shrink to a quarter: 4 cm ÷ 4 = 1 cm. (Halving to 2 cm forgets that ω is squared.)',
  },
  {
    id: 'puck-hanging-mass',
    question: 'A 0.50 kg puck moves in a circle of radius 0.30 m on a frictionless table. A light string from the puck runs through a hole at the centre of the table and holds a 0.20 kg mass that hangs at rest. How fast is the puck moving? (g = 9.8 m/s²)',
    options: ['1.1 m/s', '0.92 m/s', '2.7 m/s', '1.7 m/s'],
    correctIndex: 0,
    hint: 'The hanging mass is at rest, so the tension equals its weight, mg. That same tension is the only horizontal force on the puck, so it must equal Mv²/R.',
    explanation: 'The tension is T = mg = 0.20 × 9.8 = 1.96 N. For the puck, T = Mv²/R, so v² = TR/M = 1.96 × 0.30 / 0.50 = 1.18 and v ≈ 1.1 m/s. The other answers are slips: 0.92 uses (M + m) in the denominator, 2.7 swaps the masses, and 1.7 is √(gR) with the masses forgotten entirely.',
  },
  {
    id: 'outer-cord-tension',
    question: 'Block A (1.0 kg) and block B (2.0 kg) lie on a frictionless table and are joined in a line by cords: one from a central pivot to A, and one from A to B. A is 0.40 m from the pivot and B is 0.80 m. They whirl round at 1.0 revolution per second. What is the tension in the cord between A and B?',
    options: ['63 N', '79 N', '16 N', '32 N'],
    correctIndex: 0,
    hint: 'Look only at block B. Which cord pulls on it, and in which direction? That cord\'s tension is the only horizontal force on B, so it must equal mω²r for B.',
    explanation: 'ω = 2π rad/s, so ω² = 39.5. For B, the outer cord is the only horizontal force, so T = m_B ω² r_B = 2.0 × 39.5 × 0.80 ≈ 63 N. (79 N is the tension in the OTHER cord, and 16 N is just what block A needs for itself.)',
  },
  {
    id: 'inner-cord-tension',
    question: 'Same set-up: block A (1.0 kg) at 0.40 m and block B (2.0 kg) at 0.80 m, joined in a line by cords from the pivot to A and from A to B, whirling at 1.0 revolution per second. What is the tension in the cord between the pivot and A?',
    options: ['79 N', '63 N', '95 N', '16 N'],
    correctIndex: 0,
    hint: 'Now look at block A. The inner cord pulls it toward the centre and the outer cord pulls it away. The NET inward force on A must equal m_Aω²r_A. How big is the outer cord\'s pull?',
    explanation: 'For A: T_inner − T_outer = m_A ω² r_A = 1.0 × 39.5 × 0.40 ≈ 16 N. So T_inner = 63 + 16 ≈ 79 N. The inner cord carries both blocks\' turning forces, so it always has the biggest tension. (95 N wrongly adds 16 N a second time.)',
  },
  {
    id: 'bucket-bottom-tension',
    question: 'A 1.5 kg bucket is whirled in a vertical circle of radius 0.80 m. At the lowest point its speed is 4.0 m/s. What is the tension in the rope there? (g = 9.8 m/s²)',
    options: ['45 N', '30 N', '15 N', '59 N'],
    correctIndex: 0,
    hint: 'At the bottom the rope pulls up (toward the centre) and the weight pulls down (away from the centre). Take "toward the centre" as positive: T − mg = mv²/r.',
    explanation: 'T = mg + mv²/r = 14.7 + (1.5 × 16)/0.80 = 14.7 + 30 ≈ 45 N. The rope has to hold the bucket up AND supply the turning force. (30 N forgets the weight, 15 N is only the weight, and 59 N counts the weight twice.)',
  },
  {
    id: 'bucket-top-minimum',
    question: 'The same bucket is at the TOP of its vertical circle of radius 0.80 m. What is the slowest speed at which the rope can stay taut there? (g = 9.8 m/s²)',
    options: ['2.8 m/s', '7.8 m/s', '4.0 m/s', '0 m/s'],
    correctIndex: 0,
    hint: 'At the slowest possible speed the tension has just dropped to zero. What is then the only force pointing toward the centre, and what must it equal?',
    explanation: 'With T = 0, gravity alone supplies the turning force: mg = mv²/r, so v = √(gr) = √(9.8 × 0.80) = 2.8 m/s. The mass cancels. Below this speed gravity pulls the bucket down faster than the circle curves, and the rope goes slack. (7.8 forgets the square root, 4.0 comes from √(2gr).)',
  },
  {
    id: 'tangential-vs-radial',
    question: 'A bucket whirled in a vertical circle speeds up as it swings down and slows as it climbs. Which part of the net force changes its speed, and which changes its direction?',
    options: [
      'The part along the path (tangential) changes the speed; the part toward the centre (radial) changes the direction',
      'The part toward the centre (radial) changes the speed; the part along the path (tangential) changes the direction',
      'The part toward the centre changes both the speed and the direction',
      'Only the rope\'s tension acts, so gravity changes neither',
    ],
    correctIndex: 0,
    hint: 'A force along the direction of motion makes the object go faster or slower. A force at right angles to the motion can only bend its path.',
    explanation: 'A force along the direction of motion changes the speed, and a force at right angles to the motion changes the direction. In the vertical circle the part of gravity along the path speeds the bucket up or slows it down, while the radial part of the net force (T − mg cos φ) bends the path into a circle and must equal mv²/r.',
  },
];
